spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: Kafka Broker Default Group
    producer:
      acks: all
#      key-serializer: org.gapache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
